# This software is (C) 2022 by Eric David Moyer
# licenced under GPL 3.0 or later. See LICENSE.md for more.
cc_test(
    name = "test_greet",
    srcs = ["greeting_test.cpp"],
    deps = [
        "//src:greeting",
        "@com_google_googletest//:gtest_main",
    ],
)
